# General settings
seed: 42
num_classes: 100

# Model name
model_name: custom_cnn

# Training settings
num_epochs: 50
batch_size: 128
learning_rate: 0.001
weight_decay: 0.0001
patience: 7  # Early stopping patience

# Optimizer settings
optimizer: adam  # Options: adam, adamw, sgd
momentum: 0.9  # Used with SGD

# Learning rate scheduler settings
scheduler: reduce_on_plateau  # Options: reduce_on_plateau, cosine, step, none
step_size: 10  # Used with step scheduler
gamma: 0.1  # Used with step scheduler

# Data augmentation settings
augmentation:
  enabled: true
  random_crop: true
  random_horizontal_flip: true
  color_jitter: true
  cutout: false  # Apply random cutout augmentation

# Additional settings
save_checkpoints: true
checkpoint_interval: 5  # Save checkpoints every N epochs
visualize_results: true
